Repository aiken-lang/aiken, pull requests merged in 2022-12, with the labels that each got.

#154 Add UPLC support for 'ProtoList' & 'ProtoPair' constants
  book/src/uplc/builtins.md
  book/src/uplc/syntax.md
  crates/uplc/src/parser.rs
  crates/uplc/src/pretty.rs
Labels: documentation, uplc, parsing, testing

#156 More Parser Improvements
  crates/lang/src/format.rs
  crates/lang/src/parser.rs
  crates/lang/src/parser/error.rs
  examples/sample/lib/sample.ak
  examples/sample/validators/swap.ak
Labels: aiken lang, parsing, fmt

#157 Code Gen Improvements
  crates/cli/src/cmd/uplc/eval.rs
  crates/cli/src/lib.rs
  crates/lang/src/parser.rs
  crates/lang/src/parser/lexer.rs
  crates/lang/src/tipo/error.rs
  crates/lang/src/uplc.rs
  examples/sample/assets/swap/spend/mainnet.txt
  examples/sample/assets/swap/spend/payment_script.json
  examples/sample/assets/swap/spend/raw.uplc
  examples/sample/assets/swap/spend/script.txt
  examples/sample/assets/swap/spend/testnet.txt
  examples/sample/lib/sample.ak
  examples/sample/lib/sample/context.ak
  examples/sample/lib/sample/mint.ak
  examples/sample/lib/sample/spend.ak
  examples/sample/validators/swap.ak
Labels: aiken lang, parsing, code gen

#158 Unify Tuples
  crates/lang/src/format.rs
  crates/lang/src/tipo/environment.rs
  examples/aiken_std/lib/aiken/context.ak
  examples/aiken_std/lib/aiken/map.ak
Labels: aiken lang, typechecking, fmt

#160 Aiken Testing Framework
  CHANGELOG.md
  Cargo.lock
  crates/cli/Cargo.toml
  crates/cli/src/cmd/check.rs
  crates/cli/src/cmd/uplc/eval.rs
  crates/cli/src/lib.rs
  crates/lang/src/ast.rs
  crates/lang/src/format.rs
  crates/lang/src/parser.rs
  crates/lang/src/parser/lexer.rs
  crates/lang/src/parser/token.rs
  crates/lang/src/tipo/environment.rs
  crates/lang/src/tipo/infer.rs
  crates/project/src/error.rs
  crates/project/src/lib.rs
  crates/project/src/telemetry.rs
  crates/uplc/src/ast.rs
  crates/uplc/src/machine/cost_model.rs
  crates/uplc/src/tx/eval.rs
  examples/sample/lib/sample/thing.ak
  examples/sample/validators/swap.ak
Labels: aiken lang

#165 Refactor compile options
  crates/project/src/lib.rs
  crates/project/src/options.rs
Labels: enhancement, aiken lang

#167 update link to user manual
  README.md
Labels: documentation

#180 Refactor move helper option builder to lang
  crates/lang/src/ast.rs
  crates/project/src/lib.rs
Labels: enhancement

#181 update link to docs in the readme
  README.md
Labels: documentation, aiken lang

#182 retire mdbook
  .github/workflows/mdBook.yml
  bonnie.toml
  book/.gitignore
  book/book.toml
  book/src/SUMMARY.md
  book/src/ecosystem-overview.md
  book/src/getting-started.md
  book/src/introduction.md
  book/src/language-tour.md
  book/src/language-tour/control-flow.md
  book/src/language-tour/custom-types.md
  book/src/language-tour/functions.md
  book/src/language-tour/modules.md
  book/src/language-tour/primitive-types.md
  book/src/language-tour/variables-and-constants.md
  book/src/resources.md
  book/src/uplc.md
  book/src/uplc/builtins.md
  book/src/uplc/cli.md
  book/src/uplc/syntax.md
Labels: documentation

#183 this badge no longer exists
  README.md
Labels: documentation

#185 Aiken docs
  Cargo.lock
  crates/cli/src/cmd/docs.rs
  crates/cli/src/cmd/mod.rs
  crates/cli/src/lib.rs
  crates/cli/src/main.rs
  crates/lang/src/ast.rs
  crates/lang/src/format.rs
  crates/lang/src/parser.rs
  crates/lang/src/parser/extra.rs
  crates/lang/src/tests/parser.rs
  crates/lang/src/tipo/infer.rs
  crates/lang/src/tipo/pretty.rs
  crates/project/Cargo.toml
  crates/project/src/config.rs
  crates/project/src/docs.rs
  crates/project/src/lib.rs
  crates/project/src/module.rs
  crates/project/src/telemetry.rs
  crates/project/templates/_layout.html
  crates/project/templates/css/atom-one-dark.min.css
  crates/project/templates/css/atom-one-light.min.css
  crates/project/templates/css/index.css
  crates/project/templates/favicon.svg
  crates/project/templates/js/highlight.min.js
  crates/project/templates/js/highlightjs-aiken.js
  crates/project/templates/js/index.js
  crates/project/templates/js/lunr.min.js
  crates/project/templates/module.html
  crates/project/templates/page.html
Labels: documentation, aiken lang

#209 `aiken new` command
  crates/aiken/src/cmd/error.rs
  crates/aiken/src/cmd/new.rs
Labels: tooling

#220 support negation of int
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/ast.rs
  crates/aiken-lang/src/expr.rs
  crates/aiken-lang/src/format.rs
  crates/aiken-lang/src/parser.rs
  crates/aiken-lang/src/parser/lexer.rs
  crates/aiken-lang/src/tipo/expr.rs
  crates/aiken-lang/src/uplc.rs
Labels: parsing, typechecking, code gen

#227 validator params are now converted to type from data
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/uplc.rs
Labels: code gen
