Repository aiken-lang/aiken, pull requests merged in 2023-01, with the labels that each got.

#235 fix: nested list issues in when statements
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/uplc.rs
Labels: bug, code gen

#238 Nested list fix and Boolean constant fix
  .github/workflows/rust.yml
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/uplc.rs
Labels: bug, code gen

#248 `aiken check` make match tests flag fancier
  crates/aiken-project/src/lib.rs
  crates/aiken-project/src/options.rs
  crates/aiken/src/cmd/check.rs
Labels: test framework

#249 English auction discard assignment fix
  crates/aiken-lang/src/uplc.rs
Labels: bug, code gen

#250 error fmt was removing label
  crates/aiken-lang/src/format.rs
Labels: code formatting

#259 Basic commands for manipulating the aiken.toml
  Cargo.lock
  crates/aiken-project/Cargo.toml
  crates/aiken-project/src/config.rs
  crates/aiken-project/src/deps.rs
  crates/aiken-project/src/deps/downloader.rs
  crates/aiken-project/src/deps/manifest.rs
  crates/aiken-project/src/error.rs
  crates/aiken-project/src/lib.rs
  crates/aiken-project/src/package_name.rs
  crates/aiken-project/src/paths.rs
  crates/aiken/src/cmd/error.rs
  crates/aiken/src/cmd/mod.rs
  crates/aiken/src/cmd/new.rs
  crates/aiken/src/cmd/packages/add.rs
  crates/aiken/src/cmd/packages/clear_cache.rs
  crates/aiken/src/cmd/packages/mod.rs
  crates/aiken/src/cmd/packages/upgrade.rs
  crates/aiken/src/main.rs
Labels: tooling

#264 Add identity, always, & flip
  crates/aiken-lang/src/builtins.rs
  crates/aiken-project/src/lib.rs
  examples/acceptance_tests/041/aiken.lock
  examples/acceptance_tests/041/aiken.toml
  examples/acceptance_tests/041/lib/tests.ak
  examples/acceptance_tests/042/aiken.lock
  examples/acceptance_tests/042/aiken.toml
  examples/acceptance_tests/042/lib/tests.ak
  examples/acceptance_tests/043/aiken.lock
  examples/acceptance_tests/043/aiken.toml
  examples/acceptance_tests/043/lib/tests.ak
Labels: typechecking

#269 Error for when a validator module is imported
  crates/aiken-lang/src/tipo/environment.rs
  crates/aiken-lang/src/tipo/error.rs
Labels: typechecking

#278 Change single constr opaque types to their inner types
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/uplc.rs
Labels: code gen

#295 fix: get_variant_name was not properly traversing type args on map and data uplc types
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/tipo.rs
Labels: bug, code gen

#296 feat: handle anon zero arg functions
  crates/aiken-lang/src/uplc.rs
Labels: code gen

#304 Use IndexMap and IndexSet so the same code produces the same uplc
  Cargo.lock
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/uplc.rs
  crates/aiken-project/Cargo.toml
  crates/aiken-project/src/lib.rs
  examples/acceptance_tests/036/assets/spend/spend/mainnet.addr
  examples/acceptance_tests/036/assets/spend/spend/payment_script.json
  examples/acceptance_tests/036/assets/spend/spend/script.cbor
  examples/acceptance_tests/036/assets/spend/spend/testnet.addr
Labels: bug, code gen

#315 Assert data type to type cast
  crates/aiken-lang/src/air.rs
  crates/aiken-lang/src/builder.rs
  crates/aiken-lang/src/tipo.rs
  crates/aiken-lang/src/tipo/error.rs
  crates/aiken-lang/src/tipo/expr.rs
  crates/aiken-lang/src/uplc.rs
  crates/uplc/src/ast/builder.rs
  crates/uplc/src/machine.rs
  crates/uplc/src/machine/error.rs
  examples/acceptance_tests/040/lib/tests.ak
Labels: code gen
